projects:
- {name: 'Accounting Database Example', link: 'http://accountingdb.derrickfarris.com'}
- {name: 'Angular To-Do List App Example', link: 'http://todo.derrickfarris.com'}

files:
- {name: 'Romaja-Hangeul Converter', link: 'http://derrickfarris.com/files/RomajaConverter.jar'}

tagline: Engineer // Writer // Leader

about-me: >
  My name is Derrick Farris and I am an engineer, writer, and leader. One phrase that might best describe me is a "creator of things".
  I like creating things from something others may see as nothing. I also really enjoy discovering how things work and fixing them. 
  I often end up solving problems in ways that are considered unorthodox or haven't been proven, but I believe sometimes that's what's necessary; not every
  problem has an easy solution, but <strong>I believe no problem is unsolvable.</strong>
  <br/><br/> 
  Although I am far from having it all figured out, my passion is taking initiative and creating things — even if I don't know how it will pan out. 
  Above all, I enjoy empowering and teaching others to do the things I am adept at. What's most important to me is growing others not only in their skills, but also as people. 
  At the end of the day, I believe strongly that <strong>people are what's most important.</strong>
