projects:
- {name: 'Accounting Database Example', link: 'http://accountingdb.derrickfarris.com'}
- {name: 'Angular To-Do List App Example', link: 'http://todo.derrickfarris.com'}

files:
- {name: 'Romaja-Hangeul Converter', link: 'http://derrickfarris.com/files/RomajaConverter.jar'}
